### ISSUE TITLE
HLAtyping))chr6region.1.fastq with 0 size

### ISSUE THREAD

**Issue by ghmdsr** [jason-weirather/hla-solver#15]
I runned "shell_call_hla_type" for HLA-typing. There were not error in log, and the file named "winners.hla.txt" created well.

`winners.hla.txt : 
HLA-A hla_a_24_02_01_01 hla_a_33_03_01
HLA-B hla_b_35_01_01_01 hla_b_44_03_01
HLA-C hla_c_03_03_01 hla_c_14_03` 

However, because chr6region.1.fastq and chr6region.2.fastq file were created with no contents, I have doubts about my result.
Is it okay that these files are created with no contents?

 

Thank you for developing this tool.

**Comment by jason-weirather** [comment]
Hi ghmdsr, I recommend running the Docker written by polysolve's author 

https://hub.docker.com/r/sachet/polysolver/tags/

You may also need to use some caution with your inputs and what reference you are aligning against.  If you reference includes a lot of HLA locus variants as contigs/non-canonical chromsomes etc or if you dont also have the unaligned reads, then polysolver may not catch all the relevant reads.  But you should switch over to the regular polysolver if you are struggling since it should be better supported.

Btw, I only packaged this up and I'm not the tool creator nor am I associated with the author or his lab.  Please cite the tool's author, Sachet Shukla, and his paper if you do find this useful.  this packaging is based on his publication release of the tool and is not the most current version.

(see first line of the readme for more about this)
