### ISSUE TITLE
HLA fasta file for hg38

### ISSUE THREAD

**Issue by phuchoang1012** [jason-weirather/hla-solver#9]
Hello,

I am interested in running polysolver for data aligned to hg38. I just wonder if the abc_complete.fasta is applicable for hg38? If not, could you please advise how to extract the equivalent HLA reference file from hg38.

Thank you!

**Comment by jason-weirather** [comment]
Hi @phuchoang1012, the best option is to go with the official docker that the author maintains. He has that updated to be hg38 compatible. I haven’t tried to adopt the changes since I’ve had access to a docker friendly environment recently. I think the only change may be the intervals which it pulls in reads to map to the hla locus
